using System;
using System.Collections;
using System.IO;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Reflection;
using System.Diagnostics;
using System.Threading;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace FWEledit
{
	public partial class MainWindow : Form
	{
        private bool fwLayoutInitialized = false;
        private SplitContainer fwMainSplit;
        private TabControl fwRightTabs;
        private TabPage fwValuesTab;
        private Button fwInlinePickIconButton;
        private int fwInlinePickIconRowIndex = -1;
        private bool liveModelPreviewRefreshInProgress;
        private TabControl fwEquipmentTabs;
        private TabPage fwEquipmentTabMain;
        private TabPage fwEquipmentTabRefine;
        private TabPage fwEquipmentTabModels;
        private TabPage fwEquipmentTabOther;
        private TabPage fwDescriptionTab;
        private TextBox fwDescriptionEditor;
        private RichTextBox fwDescriptionPreview;
        private Button fwDescriptionSaveButton;
        private Label fwDescriptionStatusLabel;
        
        private readonly ElementDeletionUiService elementDeletionUiService = new ElementDeletionUiService();
        private readonly ElementCloneUiService elementCloneUiService = new ElementCloneUiService();
        private readonly ElementMoveUiService elementMoveUiService = new ElementMoveUiService();
        private readonly ElementImportExportUiService elementImportExportUiService = new ElementImportExportUiService();
        private readonly RulesExportUiService rulesExportUiService = new RulesExportUiService();
        private readonly ElementsImportExportService elementsImportExportService = new ElementsImportExportService();
        private readonly ElementsRulesExportWorkflowService elementsRulesExportWorkflowService;
        private readonly ElementImportExportWorkflowService elementImportExportWorkflowService;
        private readonly IdGenerationService idGenerationService = new IdGenerationService();
        private readonly ElementListMutationService elementListMutationService;
        private readonly ListDisplayService listDisplayService = new ListDisplayService();
        private readonly ListComboPopulationService listComboPopulationService = new ListComboPopulationService();
        private readonly IconResolutionService iconResolutionService = new IconResolutionService();
        private readonly ListSelectionWorkflowService listSelectionWorkflowService = new ListSelectionWorkflowService();
        private readonly AddonTypeDisplayService addonTypeDisplayService = new AddonTypeDisplayService();
        private readonly AddonTypeHintService addonTypeHintService = new AddonTypeHintService();
        private readonly AddonTypeOptionService addonTypeOptionService;
        private readonly AddonParamService addonParamService = new AddonParamService();
        private readonly ItemFieldClassifierService itemFieldClassifierService = new ItemFieldClassifierService();
        private readonly EquipmentFieldService equipmentFieldService = new EquipmentFieldService();
        private readonly EquipmentTabService equipmentTabService = new EquipmentTabService();
        private readonly ModelPickerCacheService modelPickerCacheService = new ModelPickerCacheService();
        private readonly ModelPickerService modelPickerService;
        private readonly ModelPackageNotificationService modelPackageNotificationService = new ModelPackageNotificationService();
        private readonly InlineIconButtonService inlineIconButtonService = new InlineIconButtonService();
        private readonly ModelPreviewService modelPreviewService = new ModelPreviewService();
        private readonly ListItemTooltipService listItemTooltipService = new ListItemTooltipService();
        private readonly ListCountExportService listCountExportService = new ListCountExportService();
        private readonly GridDoubleBufferService gridDoubleBufferService = new GridDoubleBufferService();
        private readonly PlaceholderTextService placeholderTextService = new PlaceholderTextService();
        private readonly ListRowBuilderService listRowBuilderService;
        private readonly ItemValueRowBuilderService itemValueRowBuilderService;
        private readonly ItemSelectionWorkflowService itemSelectionWorkflowService;
        private readonly ItemTooltipService itemTooltipService = new ItemTooltipService();
        private readonly ItemQualityColorService itemQualityColorService = new ItemQualityColorService();
        private readonly GridSelectionService gridSelectionService = new GridSelectionService();
        private readonly GridActiveRowService gridActiveRowService = new GridActiveRowService();
        private readonly ElementIndexResolverService elementIndexResolverService = new ElementIndexResolverService();
        private readonly IconUsageLookupService iconUsageLookupService = new IconUsageLookupService();
        private readonly PathIdResolutionService pathIdResolutionService = new PathIdResolutionService();
        private readonly SearchSuggestionService searchSuggestionService = new SearchSuggestionService();
        private readonly SearchSuggestionUiService searchSuggestionUiService = new SearchSuggestionUiService();
        private readonly SearchPlaceholderService searchPlaceholderService = new SearchPlaceholderService();
        private readonly SearchBoxUiService searchBoxUiService = new SearchBoxUiService();
        private readonly SearchUiService searchUiService = new SearchUiService();
        private readonly MainWindowSearchUiService mainWindowSearchUiService = new MainWindowSearchUiService();
        private readonly MainWindowSelectionUiService mainWindowSelectionUiService = new MainWindowSelectionUiService();
        private readonly MainWindowElementActionsUiService mainWindowElementActionsUiService = new MainWindowElementActionsUiService();
        private readonly MainWindowReplaceMappingUiService mainWindowReplaceMappingUiService = new MainWindowReplaceMappingUiService();
        private readonly MainWindowValidationUiService mainWindowValidationUiService = new MainWindowValidationUiService();
        private readonly MainWindowNpcExportUiService mainWindowNpcExportUiService = new MainWindowNpcExportUiService();
        private readonly MainWindowDialogActionsUiService mainWindowDialogActionsUiService = new MainWindowDialogActionsUiService();
        private readonly MainWindowXrefUiService mainWindowXrefUiService = new MainWindowXrefUiService();
        private readonly ValueRowIndexService valueRowIndexService = new ValueRowIndexService();
        private readonly FieldValueValidationService fieldValueValidationService = new FieldValueValidationService();
        private readonly ElementSearchService elementSearchService = new ElementSearchService();
        private readonly SearchWorkflowService searchWorkflowService = new SearchWorkflowService();
        private readonly ListSelectionUiService listSelectionUiService = new ListSelectionUiService();
        private readonly ItemSelectionUiService itemSelectionUiService = new ItemSelectionUiService();
        private readonly ValueChangeRequestBuilderService valueChangeRequestBuilderService = new ValueChangeRequestBuilderService();
        private readonly ValueChangeResultUiService valueChangeResultUiService = new ValueChangeResultUiService();
        private readonly ListSelectionRequestBuilderService listSelectionRequestBuilderService = new ListSelectionRequestBuilderService();
        private readonly ListSelectionCommandService listSelectionCommandService = new ListSelectionCommandService();
        private readonly ItemSelectionContextService itemSelectionContextService = new ItemSelectionContextService();
        private readonly ItemSelectionRequestBuilderService itemSelectionRequestBuilderService = new ItemSelectionRequestBuilderService();
        private readonly ItemSelectionCommandService itemSelectionCommandService = new ItemSelectionCommandService();
        private readonly ValueChangeSelectionService valueChangeSelectionService = new ValueChangeSelectionService();
        private readonly ValueChangeCommandService valueChangeCommandService = new ValueChangeCommandService();
        private readonly ValueRowPickerUiService valueRowPickerUiService = new ValueRowPickerUiService();
        private readonly MainWindowValueRowPickerUiService mainWindowValueRowPickerUiService = new MainWindowValueRowPickerUiService();
        private readonly ValueCompatibilityService valueCompatibilityService;
        private readonly ValueChangeService valueChangeService;
        private readonly DirtyStateTracker dirtyStateTracker = new DirtyStateTracker();
        private readonly MainWindowBootstrapService mainWindowBootstrapService = new MainWindowBootstrapService();
        private readonly MainWindowNavigationCoordinatorService mainWindowNavigationCoordinatorService = new MainWindowNavigationCoordinatorService();
        private readonly MainWindowDescriptionCoordinatorService mainWindowDescriptionCoordinatorService = new MainWindowDescriptionCoordinatorService();
        private readonly MainWindowTooltipCoordinatorService mainWindowTooltipCoordinatorService = new MainWindowTooltipCoordinatorService();
        private readonly MainWindowActionsCoordinatorService mainWindowActionsCoordinatorService = new MainWindowActionsCoordinatorService();
        private readonly MainWindowDialogsCoordinatorService mainWindowDialogsCoordinatorService = new MainWindowDialogsCoordinatorService();
        private readonly MainWindowSearchCoordinatorService mainWindowSearchCoordinatorService = new MainWindowSearchCoordinatorService();
        private readonly MainWindowSelectionCoordinatorService mainWindowSelectionCoordinatorService = new MainWindowSelectionCoordinatorService();
        private readonly MainWindowListBoxCoordinatorService mainWindowListBoxCoordinatorService = new MainWindowListBoxCoordinatorService();
        private readonly MainWindowValueInputCoordinatorService mainWindowValueInputCoordinatorService = new MainWindowValueInputCoordinatorService();
        private readonly MainWindowValuePickerCoordinatorService mainWindowValuePickerCoordinatorService = new MainWindowValuePickerCoordinatorService();
        private readonly MainWindowSaveCoordinatorService mainWindowSaveCoordinatorService = new MainWindowSaveCoordinatorService();
        private readonly MainWindowMiscCoordinatorService mainWindowMiscCoordinatorService = new MainWindowMiscCoordinatorService();
        private readonly ISessionService sessionService;
        private readonly MainWindowViewModel viewModel;
        private readonly SelectionStateService selectionStateService = new SelectionStateService();
        private readonly NavigationStateService navigationStateService = new NavigationStateService();
        private readonly NavigationSelectionService navigationSelectionService = new NavigationSelectionService();
        private readonly NavigationPersistenceService navigationPersistenceService = new NavigationPersistenceService();
        private readonly NavigationSnapshotService navigationSnapshotService = new NavigationSnapshotService();
        private readonly NavigationSnapshotUiService navigationSnapshotUiService = new NavigationSnapshotUiService();
        private readonly NavigationPersistenceUiService navigationPersistenceUiService = new NavigationPersistenceUiService();
        private readonly MainWindowNavigationUiService mainWindowNavigationUiService = new MainWindowNavigationUiService();
        private readonly MainWindowLayoutUiService mainWindowLayoutUiService = new MainWindowLayoutUiService();
        private readonly MainWindowThemeUiService mainWindowThemeUiService = new MainWindowThemeUiService();
        private readonly MainWindowVersionUiService mainWindowVersionUiService = new MainWindowVersionUiService();
        private readonly MainWindowLayoutBuilderService mainWindowLayoutBuilderService = new MainWindowLayoutBuilderService();
        private readonly MainWindowWorkflowSetupService mainWindowWorkflowSetupService = new MainWindowWorkflowSetupService();
        private readonly MainWindowAssetSetupService mainWindowAssetSetupService = new MainWindowAssetSetupService();
        private readonly MainWindowGridSetupService mainWindowGridSetupService = new MainWindowGridSetupService();
        private readonly MainWindowEventWiringService mainWindowEventWiringService = new MainWindowEventWiringService();
        private readonly MainWindowNavigationTimerService mainWindowNavigationTimerService = new MainWindowNavigationTimerService();
        private readonly MainWindowDirtyTrackingService mainWindowDirtyTrackingService = new MainWindowDirtyTrackingService();
        private readonly ElementsSessionService elementsSessionService = new ElementsSessionService();
        private readonly SaveProgressService saveProgressService = new SaveProgressService();
        private readonly SavePathService savePathService = new SavePathService();
        private readonly SaveConfirmationService saveConfirmationService = new SaveConfirmationService();
        private readonly SaveProgressUiService saveProgressUiService = new SaveProgressUiService();
        private readonly SaveConfirmationUiService saveConfirmationUiService = new SaveConfirmationUiService();
        private readonly SaveSessionUiService saveSessionUiService = new SaveSessionUiService();
        private readonly SaveContextBuilderService saveContextBuilderService = new SaveContextBuilderService();
        private readonly MainWindowSaveUiService mainWindowSaveUiService = new MainWindowSaveUiService();
        private readonly ClosePromptService closePromptService = new ClosePromptService();
        private readonly ClosePromptUiService closePromptUiService = new ClosePromptUiService();
        private readonly WindowTitleService windowTitleService = new WindowTitleService();
        private readonly ExportRulesMenuService exportRulesMenuService = new ExportRulesMenuService();
        private readonly ElementsFileInfoService elementsFileInfoService = new ElementsFileInfoService();
        private readonly ElementsInfoDialogService elementsInfoDialogService = new ElementsInfoDialogService();
        private readonly ElementsLoadService elementsLoadService = new ElementsLoadService();
        private readonly ElementsLoadWorkflowService elementsLoadWorkflowService;
        private readonly ElementsLoadUiService elementsLoadUiService = new ElementsLoadUiService();
        private readonly GameFolderLoadUiService gameFolderLoadUiService = new GameFolderLoadUiService();
        private readonly GameFolderDialogService gameFolderDialogService = new GameFolderDialogService();
        private readonly XrefMenuService xrefMenuService = new XrefMenuService();
        private readonly XrefLookupService xrefLookupService = new XrefLookupService();
        private readonly XrefLookupUiService xrefLookupUiService = new XrefLookupUiService();
        private readonly DescriptionWorkflowService descriptionWorkflowService = new DescriptionWorkflowService();
        private readonly DescriptionPreviewService descriptionPreviewService = new DescriptionPreviewService();
        private readonly DescriptionPreviewUiService descriptionPreviewUiService = new DescriptionPreviewUiService();
        private readonly DescriptionLoadService descriptionLoadService = new DescriptionLoadService();
        private readonly DescriptionRuntimeService descriptionRuntimeService = new DescriptionRuntimeService();
        private readonly DescriptionUiService descriptionUiService = new DescriptionUiService();
        private readonly DescriptionRuntimeBridgeService descriptionRuntimeBridgeService = new DescriptionRuntimeBridgeService();
        private readonly DescriptionLoadUiService descriptionLoadUiService = new DescriptionLoadUiService();
        private readonly DescriptionFlushUiService descriptionFlushUiService = new DescriptionFlushUiService();
        private readonly DescriptionIdRemapService descriptionIdRemapService = new DescriptionIdRemapService();
        private readonly MainWindowDescriptionUiService mainWindowDescriptionUiService = new MainWindowDescriptionUiService();
        private readonly MainWindowElementsLoadUiService mainWindowElementsLoadUiService = new MainWindowElementsLoadUiService();
        private readonly ItemDescriptionFileService itemDescriptionFileService = new ItemDescriptionFileService();
        private readonly ElementsValidationService elementsValidationService = new ElementsValidationService();
        private readonly UniqueIdValidationService uniqueIdValidationService = new UniqueIdValidationService();
        private readonly ErrorLoggingService errorLoggingService = new ErrorLoggingService();
        private readonly DialogService dialogService = new DialogService();
        private readonly ComboBoxThemeRendererService comboBoxThemeRendererService = new ComboBoxThemeRendererService();
        private readonly ThemeComboBoxDrawService themeComboBoxDrawService = new ThemeComboBoxDrawService();
        private readonly TextExportDialogService textExportDialogService = new TextExportDialogService();
        private readonly IconListAvailabilityService iconListAvailabilityService = new IconListAvailabilityService();
        private readonly ToolPreviewService toolPreviewService = new ToolPreviewService();
        private readonly EditorWindowService editorWindowService;
        private readonly AboutWindowCommandService aboutWindowCommandService = new AboutWindowCommandService();
        private readonly ClassMaskCommandService classMaskCommandService = new ClassMaskCommandService();
        private readonly ConfigWindowCommandService configWindowCommandService = new ConfigWindowCommandService();
        private readonly RulesWindowService rulesWindowService = new RulesWindowService();
        private readonly RulesService rulesService = new RulesService();
        private readonly ExportRulesCommandService exportRulesCommandService = new ExportRulesCommandService();
        private readonly ReplaceService replaceService = new ReplaceService();
        private readonly ReplaceMappingFileService replaceMappingFileService = new ReplaceMappingFileService();
        private readonly ElementsReplaceService elementsReplaceService = new ElementsReplaceService();
        private readonly ReplaceWindowCommandService replaceWindowCommandService = new ReplaceWindowCommandService();
        private readonly FieldReplaceUiService fieldReplaceUiService = new FieldReplaceUiService();
        private readonly InfoDialogUiService infoDialogUiService = new InfoDialogUiService();
        private readonly ConfigWindowUiService configWindowUiService = new ConfigWindowUiService();
        private readonly ElementExportUiService elementExportUiService = new ElementExportUiService();
        private readonly OffsetChangeUiService offsetChangeUiService = new OffsetChangeUiService();
        private readonly RulesWindowUiService rulesWindowUiService = new RulesWindowUiService();
        private readonly ClassMaskUiService classMaskUiService = new ClassMaskUiService();
        private readonly ReplaceMappingUiService replaceMappingUiService = new ReplaceMappingUiService();
        private readonly SkillValidationService skillValidationService = new SkillValidationService();
        private readonly PropertyValidationService propertyValidationService = new PropertyValidationService();
        private readonly TomeValidationService tomeValidationService = new TomeValidationService();
        private readonly ProbabilityValidationService probabilityValidationService = new ProbabilityValidationService();
        private readonly ValidationUiService validationUiService = new ValidationUiService();
        private readonly NpcExportService npcExportService = new NpcExportService();
        private readonly FieldCompareService fieldCompareService = new FieldCompareService();
        private readonly FieldCompareWorkflowService fieldCompareWorkflowService = new FieldCompareWorkflowService();
        private readonly FieldCompareCommandService fieldCompareCommandService = new FieldCompareCommandService();
        private readonly FieldReplaceService fieldReplaceService = new FieldReplaceService();
        private readonly ElementClipboardService elementClipboardService = new ElementClipboardService();
        private readonly ElementDeleteCommandService elementDeleteCommandService = new ElementDeleteCommandService();
        private readonly ElementCloneCommandService elementCloneCommandService = new ElementCloneCommandService();
        private readonly ElementExportCommandService elementExportCommandService = new ElementExportCommandService();
        private readonly ElementImportCommandService elementImportCommandService = new ElementImportCommandService();
        private readonly ElementBatchAddCommandService elementBatchAddCommandService = new ElementBatchAddCommandService();
        private readonly ElementMoveCommandService elementMoveCommandService = new ElementMoveCommandService();
        private readonly ElementsJoinWorkflowService elementsJoinWorkflowService = new ElementsJoinWorkflowService();
        private readonly ElementsJoinUiService elementsJoinUiService = new ElementsJoinUiService();
        private readonly NpcAiExportService npcAiExportService = new NpcAiExportService();
        private readonly NpcExportUiService npcExportUiService = new NpcExportUiService();
        private readonly QuestOverflowService questOverflowService = new QuestOverflowService();
        private readonly QuestOverflowUiService questOverflowUiService = new QuestOverflowUiService();
        private readonly ColorShadeService colorShadeService = new ColorShadeService();
        private readonly ConfigFileService configFileService = new ConfigFileService();
        private readonly InfoMessageService infoMessageService = new InfoMessageService();
        private readonly ItemListThemeService itemListThemeService = new ItemListThemeService();
        private readonly ThemeUiService themeUiService = new ThemeUiService();
        private readonly SplitContainerSizingService splitContainerSizingService = new SplitContainerSizingService();
        private readonly StartupSessionService startupSessionService = new StartupSessionService();
        private readonly ItemTooltipUiService itemTooltipUiService = new ItemTooltipUiService();
        private readonly ListItemHoverTooltipService listItemHoverTooltipService = new ListItemHoverTooltipService();
        private readonly ValueInputPlaceholderService valueInputPlaceholderService = new ValueInputPlaceholderService();
        private readonly SetValueActionService setValueActionService = new SetValueActionService();
        private readonly OffsetUpdateService offsetUpdateService = new OffsetUpdateService();
        private readonly ItemQualityRowStyleService itemQualityRowStyleService = new ItemQualityRowStyleService();
        private readonly DirtyTrackingUiService dirtyTrackingUiService = new DirtyTrackingUiService();
        private readonly FieldIndexLookupService fieldIndexLookupService = new FieldIndexLookupService();
        private readonly DdsIconService ddsIconService = new DdsIconService();
        private readonly ReplaceWindowUiService replaceWindowUiService = new ReplaceWindowUiService();
        private readonly ElementImportUiService elementImportUiService = new ElementImportUiService();
        private readonly ClipboardUiService clipboardUiService = new ClipboardUiService();
        private readonly XrefItemUiService xrefItemUiService = new XrefItemUiService();
        private readonly CursorScopeService cursorScopeService = new CursorScopeService();
        private ListBox searchSuggestionList;
        private System.Windows.Forms.Timer navigationPersistTimer;
        private static readonly List<QualityOption> ItemQualityOptions = ItemQualityCatalog.Options;
    }
}


