using System;
using System.Collections.Generic;
using System.Globalization;

namespace FWEledit
{
    public static class EquipmentUsingTypeCatalog
    {
        private static readonly List<EquipmentMaskOption> options = new List<EquipmentMaskOption>
        {
            new EquipmentMaskOption { Mask = 1u, Label = "Drop Equipment", Description = "Equipment generated by drop/re-identification pools. Usually PvE-style random attributes." },
            new EquipmentMaskOption { Mask = 2u, Label = "Crafted Equipment", Description = "Equipment generated by production/crafting pools." },
            new EquipmentMaskOption { Mask = 4u, Label = "Arena Equipment", Description = "Equipment generated by arena/PvP pools. Usually resistance and critical defense style attributes." },
            new EquipmentMaskOption { Mask = 8u, Label = "Reserved 1", Description = "Reserved equipment using type from the client table." },
            new EquipmentMaskOption { Mask = 16u, Label = "Reserved 2", Description = "Reserved equipment using type from the client table." },
            new EquipmentMaskOption { Mask = 32u, Label = "Reserved 3", Description = "Reserved equipment using type from the client table." }
        };

        public static IList<EquipmentMaskOption> Options
        {
            get { return options; }
        }

        public static bool IsEquipmentUsingTypeFieldName(string fieldName)
        {
            return string.Equals(fieldName, "equip_usingtype_mask", StringComparison.OrdinalIgnoreCase);
        }

        public static string FormatDisplay(string rawValue)
        {
            uint value;
            if (!EquipmentMaskCatalog.TryParseValue(rawValue, out value))
            {
                return rawValue ?? string.Empty;
            }

            if (value == 0)
            {
                return "None";
            }

            List<string> labels = new List<string>();
            uint remaining = value;
            for (int i = 0; i < options.Count; i++)
            {
                EquipmentMaskOption option = options[i];
                if (option == null || (value & option.Mask) != option.Mask)
                {
                    continue;
                }

                labels.Add(option.Label ?? string.Empty);
                remaining &= ~option.Mask;
            }

            if (remaining != 0)
            {
                labels.Add("Unknown (0x" + remaining.ToString("X", CultureInfo.InvariantCulture) + ")");
            }

            return labels.Count == 0 ? rawValue ?? string.Empty : string.Join(", ", labels.ToArray());
        }

        public static string NormalizeInput(string value)
        {
            if (value == null)
            {
                return string.Empty;
            }

            uint parsed;
            if (EquipmentMaskCatalog.TryParseValue(value, out parsed))
            {
                return parsed.ToString(CultureInfo.InvariantCulture);
            }

            return value.Trim();
        }
    }
}
