//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWEledit.Properties
{


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
	{

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default
		{
			get
			{
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string LastGameFolder
		{
			get
			{
				return ((string)(this["LastGameFolder"]));
			}
			set
			{
				this["LastGameFolder"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int LastListIndex
		{
			get
			{
				return ((int)(this["LastListIndex"]));
			}
			set
			{
				this["LastListIndex"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("-1")]
		public int LastItemId
		{
			get
			{
				return ((int)(this["LastItemId"]));
			}
			set
			{
				this["LastItemId"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string LastRunVersion
		{
			get
			{
				return ((string)(this["LastRunVersion"]));
			}
			set
			{
				this["LastRunVersion"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool ModelPreviewUseHardware
		{
			get
			{
				return ((bool)(this["ModelPreviewUseHardware"]));
			}
			set
			{
				this["ModelPreviewUseHardware"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int ModelPreviewBackend
		{
			get
			{
				return ((int)(this["ModelPreviewBackend"]));
			}
			set
			{
				this["ModelPreviewBackend"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool ModelPreviewCameraHasState
		{
			get
			{
				return ((bool)(this["ModelPreviewCameraHasState"]));
			}
			set
			{
				this["ModelPreviewCameraHasState"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public float ModelPreviewCameraYaw
		{
			get
			{
				return ((float)(this["ModelPreviewCameraYaw"]));
			}
			set
			{
				this["ModelPreviewCameraYaw"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public float ModelPreviewCameraPitch
		{
			get
			{
				return ((float)(this["ModelPreviewCameraPitch"]));
			}
			set
			{
				this["ModelPreviewCameraPitch"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public float ModelPreviewCameraZoom
		{
			get
			{
				return ((float)(this["ModelPreviewCameraZoom"]));
			}
			set
			{
				this["ModelPreviewCameraZoom"] = value;
			}
		}
	}
}
